# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8c4177449d38616948acb21a2c9955523ab69ce3fc6c0bd8883d2aff59c0762f5c3def0920a825b85299ba29e14603c3d98d9bd94cfd6627d65376d40ef739db

test:
  secret_key_base: 34c353465f5113d092bf9eefa58112b62aceb081a5f73a69ad2678dffbe0ce6e4aece86d8def7a641cdc9933eb268b0cb4db090aa8e5904cf2db76d1f453e1e0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
